[profile.default]
src = "src"
out = "out"
test = "test"
libs = ['node_modules', 'lib']
fs_permissions = [{ access = "read", path = "./" }]
solc = "0.8.25"
evm_version = 'cancun'

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
base_goerli = "https://goerli.base.org"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASE_EXPLORER_API_KEY}" }
base_sepolia = { key = "${BASE_EXPLORER_API_KEY}" }
arbitrum_sepolia = { key = "${ARB_EXPLORER_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
